if game.PlaceId == 79268393072444 then--出售柠檬
loadstring(game:HttpGet("https://raw.githubusercontent.com/WuMing-YYDS/FuWuQi/refs/heads/main/%E5%90%8D-%E5%87%BA%E5%94%AE%E6%9F%A0%E6%AA%AC%5B%E5%8A%A0%E5%AF%86%5D.LUA"))()

if game.PlaceId == 79268393072444 then--力量传奇
loadstring(game:HttpGet("https://raw.githubusercontent.com/WuMing-YYDS/FuWuQi/refs/heads/main/%E5%90%8D-%E5%8A%9B%E9%87%8F%E4%BC%A0%E5%A5%87%5B%E5%8A%A0%E5%AF%86%5D.LUA"))()

if game.PlaceId == 79268393072444 then--自然灾害
loadstring(game:HttpGet("https://raw.githubusercontent.com/WuMing-YYDS/FuWuQi/refs/heads/main/%E5%90%8D-%E8%87%AA%E7%84%B6%E7%81%BE%E5%AE%B3%5B%E5%8A%A0%E5%AF%86%5D.LUA"))()

if game.PlaceId == 79268393072444 then--河北唐县
loadstring(game:HttpGet("https://raw.githubusercontent.com/WuMing-YYDS/FuWuQi/refs/heads/main/%E5%90%8D-%E6%B2%B3%E5%8C%97%E5%94%90%E5%8E%BF%5B%E5%8A%A0%E5%AF%86%5D.LUA"))()

else--通用
local msg = Instance.new("Message",workspace)
msg.Text = "不支持该服务器"
wait(1.8)
msg:Destroy()
end
